name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
        matrix:
            features: [ "", "arrayvec", "heapless", "vec" ]
            rust: [ "nightly", "nightly-2023-05-31" ]
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
    - name: Build
      run: cargo build --verbose --no-default-features ${{ matrix.features == '' && ' ' || format('--features {0}', matrix.features) }}
    - name: Run tests
      run: cargo test --verbose --no-default-features ${{ matrix.features == '' && ' ' || format('--features {0}', matrix.features) }}
